site_name: Kotlin Channel Event Bus
site_url: https://hoc081098.github.io/kotlin-channel-event-bus/docs/0.x
repo_name: kotlin-channel-event-bus
repo_url: https://github.com/Kotlin-Multiplatform-Foundation/kotlin-channel-event-bus
site_description: "Multi-keys, multi-producers, single-consumer event bus backed by Kotlinx Coroutines Channels"
site_author: Petrus Nguyễn Thái Học
remote_branch: gh-pages
edit_uri: edit/master/docs/

copyright: 'Copyright &copy; 2023 Petrus Nguyễn Thái Học.'

theme:
  name: 'material'
  favicon: images/logo.jpeg
  logo: images/logo.jpeg
  palette:
    primary: 'deep purple'
    accent: 'white'
  features:
    - toc.integrate

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - tables

nav:
  - 'Overview': index.md
  - 'API': API
